### ISSUE TITLE
ionic image s3 upload issue in running in mobile

### ISSUE THREAD

**Issue by mishranu2** [toddhalfpenny/mobilecaddy-aws-upload#1]
## Hey! I posted the question and am still stuck with it. ionic image s3 upload runs fine on ionic serve but throws the following error in debugger when running on android phone. How to resolve it? did you face the issue on running on android phone?

Working fine on chrome using ionic serve, but not working on device. Returns this error on debugging in app console. 
Please help fix. 
TypeError: Object function Object() { [native code] } has no method 'assign'
at Object.b (file:///android_asset/www/lib/s3-image-uploader/dist/image-uploader.bundle.min.js:38:25746)
at new (file:///android_asset/www/js/app.js:428:23)
at Object.invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17995:19)
at $controllerInit (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:23397:34)
at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22335:34)
at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21703:13)
at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21706:13)
at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22387:24)
at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21703:13)
at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22387:24) ionic.bundle.js:26794
(anonymous function) ionic.bundle.js:26794
(anonymous function) ionic.bundle.js:23507
Scope.$broadcast ionic.bundle.js:30720
$state.transition.resolved.then.$state.transition ionic.bundle.js:52157
processQueue ionic.bundle.js:29127
(anonymous function) ionic.bundle.js:29143
Scope.$eval ionic.bundle.js:30395
Scope.$digest ionic.bundle.js:30211
Scope.$apply ionic.bundle.js:30503
(anonymous function) ionic.bundle.js:65426
defaultHandlerWrapper ionic.bundle.js:16787
eventHandler ionic.bundle.js:16775
triggerMouseEvent ionic.bundle.js:2953
tapClick ionic.bundle.js:2942
tapTouchEnd ionic.bundle.js:3069

**Comment by toddhalfpenny** [comment]
Hi Mish. Do you see anything in the network tab in devtools? Also, could you use the non-min version of the image-uploader so the console line numbers become more useful?
